version: "3.7"

services:
  qtweet:
    build: .
    image: navenn_t/qtweet
    environment:
      - TZ=${TIMEZONE}
    container_name: qtweet
    restart: on-failure
    environment:
      PGHOST: postgres
      PGDATABASE: qtweetData
      PGPASSWORD: ${DB_PASSWORD}
      PGUSER: ${DB_USER}
    depends_on:
      - postgres

  postgres:
    image: postgres:12.1-alpine
    restart: always
    container_name: postgres
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: qtweetData
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DEFAULT_LANG: ${DEFAULT_LANG}